<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129111929 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, address_id INT NOT NULL, label VARCHAR(255) NOT NULL, is_current BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BE136DCB7E3C61F9 ON user_location (owner_id)');
        $this->addSql('CREATE INDEX IDX_BE136DCBF5B7AF75 ON user_location (address_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USER_LOCATION ON user_location (owner_id, address_id, label)');
        $this->addSql('ALTER TABLE user_location ADD CONSTRAINT FK_BE136DCB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_location ADD CONSTRAINT FK_BE136DCBF5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_location DROP CONSTRAINT FK_BE136DCB7E3C61F9');
        $this->addSql('ALTER TABLE user_location DROP CONSTRAINT FK_BE136DCBF5B7AF75');
        $this->addSql('DROP TABLE user_location');
    }
}
