<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251130141039 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE edition_draft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, artist_canonical VARCHAR(255) NOT NULL, record_canonical VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, input JSON NOT NULL, discogs JSON DEFAULT NULL, ai JSON DEFAULT NULL, resolved JSON DEFAULT NULL, duplicate_probe JSON DEFAULT NULL, attempts INT NOT NULL, last_error VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BCC39C1C7E3C61F9 ON edition_draft (owner_id)');
        $this->addSql('CREATE INDEX idx_draft_status ON edition_draft (status)');
        $this->addSql('CREATE INDEX idx_draft_expires_at ON edition_draft (expires_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EDITION_DRAFT ON edition_draft (owner_id, artist_canonical, record_canonical)');
        $this->addSql('ALTER TABLE edition_draft ADD CONSTRAINT FK_BCC39C1C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE edition_draft DROP CONSTRAINT FK_BCC39C1C7E3C61F9');
        $this->addSql('DROP TABLE edition_draft');
    }
}
