<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129114657 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE edition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, record_id INT NOT NULL, cover_file VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A891181F7E3C61F9 ON edition (owner_id)');
        $this->addSql('CREATE INDEX IDX_A891181F4DFD750C ON edition (record_id)');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F4DFD750C FOREIGN KEY (record_id) REFERENCES record (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE edition DROP CONSTRAINT FK_A891181F7E3C61F9');
        $this->addSql('ALTER TABLE edition DROP CONSTRAINT FK_A891181F4DFD750C');
        $this->addSql('DROP TABLE edition');
    }
}
