<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129112348 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, year_original VARCHAR(255) NOT NULL, cover_url VARCHAR(255) DEFAULT NULL, cover_hash VARCHAR(255) DEFAULT NULL, discogs_master_id VARCHAR(255) DEFAULT NULL, discogs_release_id VARCHAR(255) DEFAULT NULL, source_confidence INT NOT NULL, artist_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B349F91B7970CF8 ON record (artist_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_RECORD ON record (artist_id, title, year_original)');
        $this->addSql('ALTER TABLE record ADD CONSTRAINT FK_9B349F91B7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE record DROP CONSTRAINT FK_9B349F91B7970CF8');
        $this->addSql('DROP TABLE record');
    }
}
